Derive default expression language dynamically
What

Before this commit, default expression language was determined at the
first occasion it was needed (and stayed cached). Now this behavior is
changed: default is determined each time.

Why

The immediate reason was failing admin-gui tests, even though the
sysconfig used has still the original default (Groovy). The problem
was that the sysconfig was loaded twice (once from initial objects,
then from specific test config).

But more generally, we need this to be dynamic: the system should react
to changes in sysconfig object immediately.

The performance penalty is not that high, given that the config object
is usually cached. (The only issue could be if there's a schema
exception: log will be full of exceptions then.)

Task: 12424