Tentatively fix MID-4383: (...) prismContext is null
The problem with MID-4383: "UserProfile Projection tab:
java.lang.IllegalStateException: prismContext is null" is that
prismContext is null in ShadowType->ResourceType (supposedly)
after session objects deserialization. This commit provides
a temporary fix, until session objects are treated in a more
systematic way.